// Generates src/locales.ts from _locales/<lang>/messages.json.
//
// _locales/ is the single source of truth for all UI strings:
//   - Chrome reads it natively for manifest __MSG_*__ substitution and chrome.i18n
//   - This script flattens it into a bundled TS map for the content script, which
//     needs synchronous string access without an async chrome.i18n round-trip.
//
// Run via `npm run build` (build.mjs invokes this first). Never hand-edit src/locales.ts.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const LOCALES_DIR = '_locales';
const OUT = 'src/locales.ts';
const DEFAULT_LOCALE = 'en';

/** Read one _locales/<lang>/messages.json and flatten { key: { message } } -> { key: message }. */
function readLocale(lang) {
  const raw = JSON.parse(readFileSync(join(LOCALES_DIR, lang, 'messages.json'), 'utf8'));
  const flat = {};
  for (const [key, entry] of Object.entries(raw)) flat[key] = entry.message;
  return flat;
}

const langs = readdirSync(LOCALES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort((a, b) => (a === DEFAULT_LOCALE ? -1 : b === DEFAULT_LOCALE ? 1 : a.localeCompare(b)));

if (!langs.includes(DEFAULT_LOCALE)) {
  throw new Error(`gen-locales: missing default locale "_locales/${DEFAULT_LOCALE}"`);
}

const locales = Object.fromEntries(langs.map((l) => [l, readLocale(l)]));

// Fail the build on key drift rather than silently shipping untranslated UI.
const baseKeys = Object.keys(locales[DEFAULT_LOCALE]);
const drift = [];
for (const lang of langs) {
  if (lang === DEFAULT_LOCALE) continue;
  const missing = baseKeys.filter((k) => !(k in locales[lang]));
  const extra = Object.keys(locales[lang]).filter((k) => !baseKeys.includes(k));
  if (missing.length) drift.push(`  ${lang}: missing ${missing.join(', ')}`);
  if (extra.length) drift.push(`  ${lang}: unknown key(s) ${extra.join(', ')}`);
}
if (drift.length) {
  throw new Error(`gen-locales: locale key drift vs "${DEFAULT_LOCALE}":\n${drift.join('\n')}`);
}

const body = JSON.stringify(locales, null, 2)
  .split('\n')
  .map((line, i) => (i === 0 ? line : '  ' + line))
  .join('\n');

writeFileSync(
  OUT,
  `// AUTO-GENERATED by gen-locales.mjs from _locales/. Do not edit directly.\n` +
    `// To change a string, edit _locales/<lang>/messages.json and run \`npm run build\`.\n` +
    `export const LOCALES: Record<string, Record<string, string>> = ${body};\n`,
);

console.log(`🌍 locales: ${langs.length} languages × ${baseKeys.length} keys -> ${OUT}`);
